name: workflow-connector
displayName: Signavio Workflow Connector
description: >
  A web service which provides a Workflow Accelerator conform
  RESTful API on top of standard SQL Databases
port: 443
database:
  driver: sqlite3
  url: test.db 
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
