# Using an Oracle database
---
name: workflow-connector
displayName: Signavio Workflow Connector
description: >
  A web service which provides a Workflow Accelerator conform
  RESTful API on top of standard SQL Databases
port: 443
database:
  driver: goracle
  # url = username:password@address/service_name
  url: oracle://john:84mj29rSgHz@172.17.8.2/test
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  # password = Foobar
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
...
# Using a Postgres database
---
name: workflow-connector
displayName: Signavio Workflow Connector
description: >
  A web service which provides a Workflow Accelerator conform
  RESTful API on top of standard SQL Databases
port: 443
database:
  driver: postgres
  # You can find the list of supported parameters
  # at https://godoc.org/github.com/lib/pq
  url: postgres://bob:l120arSgHz@172.17.8.2/test?sslmode=verify-full
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  # password = Foobar
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
...
# Using a mysql database
---
name: workflow-connector
displayName: Signavio Workflow Connector
description: >
  A web service which provides a Workflow Accelerator conform
  RESTful API on top of standard SQL Databases
port: 443
database:
  driver: mysql
  # url = username:password@protocol(address)/dbname?param=value
  # You can find the list of supported parameters
  # at https://github.com/go-sql-driver/mysql
  url: bob:l120arSgHz@tcp(172.17.8.2:3306)/test?parseTime=true
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  # password = Foobar
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
...
